version: "3.8"

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: personal-palette-db
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${USERPASS}
    ports:
      - "5433:5432"
    volumes:
      - personal-palette-db:/var/lib/postgresql/data

volumes:
  personal-palette-db: